### ISSUE TITLE
Cloudflare Status API might be useful

### ISSUE THREAD

**Issue by kLiHz** [Netrvin/cloudflare-colo-list#2]
It seems that there are several APIs provided at <https://www.cloudflarestatus.com/api>, where JSON-formatted data center information can be found in [Components](https://www.cloudflarestatus.com/api/v2/components.json). With this API, parsing from HTML may not be necessary anymore.

**Comment by Netrvin** [comment]
Thanks for your suggestion. Updated in commit 096d9e38bf5f7086d6d68934c9db73c139749d46.
